---
- name: Upload package
  nfvis_upload:
    host: "{{ nfvis_ip }}"
    user: "{{ nfvis_user }}"
    password: "{{ nfvis_password }}"
    file: "{{ nfvis_package_dir }}/{{ package_name }}.tar.gz"
  register: command_results
  delegate_to: localhost

- debug:
    var: command_results

#- name: Register package
#  uri:
#    url: "https://{{ nfvis_ip }}/api/config/vm_lifecycle/images"
#    user: "{{ nfvis_user }}"
#    password: "{{ nfvis_password }}"
#    method: POST
#    headers:
#      Content-Type: "application/vnd.yang.data+json"
#    body_format: json
#    body:
#      image:
#        name: "{{ package_name }}"
#        src: "file://data/intdatastore/uploads/{{ package_name }}.tar.gz"
#    status_code: [ 201 ]
#    return_content: yes
#    validate_certs: no
#  failed_when: uri_results.status not in [201, 409]
#  changed_when: uri_results.status == 201
#  no_log: false  # Don't show output as your password will be on the URI string
#  register: uri_results
#  delegate_to: localhost